In [1]:
import os
from os.path import isfile, join
import pandas_datareader as pdr
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statistics
from statistics import mean, mode, median, stdev
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler

In [2]:
tiingo_api_key = os.environ['TIINGO_API_KEY']
iex_api_key = os.environ['IEX_API_KEY']

In [3]:
# File containing all tickers listed by NASDAQ-100
tickers_file = 'ndxt_tickers.txt'
data_dir = 'data/'
raw_data_dir = data_dir + 'raw/'
processed_data_dir = data_dir + 'processed/'
final_data_dir = data_dir + 'final/'
time_range = [1, 5, 10, 20, 90, 270]

if not os.path.exists(raw_data_dir):
    os.makedirs(raw_data_dir)
if not os.path.exists(processed_data_dir):
    os.makedirs(processed_data_dir)
if not os.path.exists(final_data_dir):
    os.makedirs(final_data_dir)
for t in time_range:
    if not os.path.exists(final_data_dir+str(t)+'/'):
            os.makedirs(final_data_dir+str(t)+'/')

In [4]:
# Read all the tickers to be used in the data
ndxt_tickers = []
with open(data_dir+tickers_file) as f:
    for ticker in f:
        ndxt_tickers.append(ticker.replace('\n', ''))

In [6]:
# Code for downloading data and saving it, use only when necessary
'''
raw_stock_data_tiingo = []
raw_stock_data_iex = []
error_tickers = []

for ticker in sorted(ndxt_tickers):
    try:
        raw_stock_data_tiingo.append(pdr.get_data_tiingo(ticker, api_key= tiingo_api_key))
    except:
        error_tickers.append(ticker)

raw_index_data_yahoo = yf.download('^NDXT', period='5y')
# Save each stock data in a CSV file
for t in raw_stock_data_tiingo:
    t.to_csv(raw_data_dir + t.index.values[0][0] + '.csv')
raw_index_data_yahoo.to_csv(raw_data_dir + '^NDXT.csv')
'''

"\nraw_stock_data_tiingo = []\nraw_stock_data_iex = []\nerror_tickers = []\n\nfor ticker in sorted(ndxt_tickers):\n    try:\n        raw_stock_data_tiingo.append(pdr.get_data_tiingo(ticker, api_key= tiingo_api_key))\n    except:\n        error_tickers.append(ticker)\n\nraw_index_data_yahoo = yf.download('^NDXT', period='5y')\n# Save each stock data in a CSV file\nfor t in raw_stock_data_tiingo:\n    t.to_csv(raw_data_dir + t.index.values[0][0] + '.csv')\nraw_index_data_yahoo.to_csv(raw_data_dir + '^NDXT.csv')\n"

In [7]:
# Read downloaded data from files
raw_stock_data = []
raw_index_data_filename = '^NDXT.csv'
raw_stock_data_filenames = [f+'.csv' for f in ndxt_tickers]
raw_index_df = pd.read_csv(raw_data_dir + raw_index_data_filename)

for filename in raw_stock_data_filenames:
    raw_stock_data.append(pd.read_csv(raw_data_dir + filename))

In [8]:
# Check for incomplete(dates) stocks and remove them
stock_record_count = mode([len(data) for data in raw_stock_data] + [len(raw_index_df)])
for i, t in enumerate(raw_stock_data):
    if len(t) != stock_record_count: 
        raw_stock_data.pop(i)
        print('Element removed.')

In [9]:
# Check for missing values
for i, t in enumerate(raw_stock_data):
    if t.isnull().any().any(): print('Missing data.')

In [10]:
# Check that all stock data have the same dates, not the most optimal way to calculate it yet since its O(n^2)
equal = True
for i in range(len(raw_stock_data)):
    for j in range(len(raw_stock_data)):
        if not (raw_stock_data[i]['date'] == raw_stock_data[j]['date']).all(): equal = False
print('Data has equal dates in all rows: ' + str(equal))
assert equal

Data has equal dates in all rows: True

In [11]:
# Reformat date in stocks dataframes 
for data in raw_stock_data:
    data['date'] = data['date'].map(lambda x: x.split()[0])
    
# Reformat date in index dataframe
#mon_to_num = {'Jan':'01', 'Feb':'02', 'Mar':'03', 'Apr':'04', 'May':'05', 'Jun':'06', 'Jul':'07', 'Aug':'08', 'Sep':'09', 'Oct':'10', 'Nov':'11', 'Dec':'12'}

#raw_index_df['Date'] = raw_index_df['Date'].map(lambda x: x.split()[2]+'-'+ mon_to_num[x.split()[0]] +'-'+x.split()[1].strip(','))

raw_index_df.drop(columns='Volume', inplace=True)

# Rename index columns
raw_index_df.columns = ['date', 'open', 'high', 'low', 'close', 'adjClose']

In [12]:
# Assign symbol and date as index identifiers for every stock record

for data in raw_stock_data:
    data.set_index(['symbol', 'date'], inplace=True, drop=True)
    
# Assign date as index identifier for index records as well

raw_index_df.set_index(['date'], inplace=True, drop=True)


# Concatenate all stock datadrames into one

#raw_stock_df = pd.concat(raw_stock_data)


# Remove unnecessary information

for df in raw_stock_data: df.drop(columns=['divCash', 'splitFactor'], inplace=True)

In [13]:
# Find the oldest final date and newest starting date

last_dates = [raw_index_df.index[-1]]
first_dates = [raw_index_df.index[0]]

for df in raw_stock_data:
    dates = []
    
    for idx in df.index:
        dates.append(idx[1])
    
    last_dates.append(max(dates))
    first_dates.append(min(dates))

last_date = min(last_dates)
first_date = max(first_dates)
print(last_date)
print(first_date)

2019-10-15
2014-10-16

In [14]:
# Make sure both DataFrames have the same final date (as close to today as possible)

while(raw_index_df.index[0] > last_date):
    raw_index_df.pop(raw_index_df.index[0])

while(raw_index_df.index[-1] < first_date):
    raw_index_df.pop(raw_index_df.index[-1])
        
for df in raw_stock_data:
    while(df.index[0][1] > last_date):
        df.pop(df.index[0])
    while(df.index[-1][1] < first_date):
        df.pop(df.index[-1])
        
# Reverse stock and index records
for df in raw_stock_data:
    df = df.sort_index(ascending=False, inplace=True)
raw_index_df = raw_index_df.iloc[::-1]

In [15]:
# DataFrames have been processed and not considered raw anymore
stocks_df = raw_stock_data
index_df = pd.DataFrame(raw_index_df)

In [16]:
def labels(stock_df, since = 1):
    stock_df.drop(columns='y_'+str(since), inplace=True, errors='ignore')
    labels = []
    for i in range(len(stock_df)):
        try:
            assert i-since >= 0
            today = stock_df.iloc[i]['close']
            future = stock_df.iloc[i-since]['close']
            labels.append(1 if future>today else 0)
        except:
            labels.append(None)
    stock_df.insert(loc=0, column='y_'+str(since), value=labels)

In [17]:
def change(stock_df, period = 1):
    stock_df.drop(columns='change', inplace=True, errors='ignore')
    change = []
    for i in range(len(stock_df)):
        try:
            today = stock_df.iloc[i]['close']
            previous = stock_df.iloc[i+period]['close']
            change.append(100*(today-previous)/previous)
        except:
            change.append(None)
    stock_df.insert(loc=0, column='change', value=change)

In [18]:
def PMO(stock_df, period = 50):
    stock_df.drop(columns='PMO', inplace=True, errors='ignore')
    pmo = []
    for i in range(len(stock_df)):
        try:
            today = stock_df.iloc[i]['close']
            previous = stock_df.iloc[i+period]['close']
            pmo.append(today - previous)
        except:
            pmo.append(None)
    stock_df.insert(loc=0, column='PMO', value=pmo)

In [19]:
def RSI(stock_df, period = 50):
    stock_df.drop(columns='RSI', inplace=True, errors='ignore')
    rsi = []
    for i in range(len(stock_df)):
        try:
            rsi_value = 0
            pos = []
            neg = []
            
            for j in range(period):
                change = stock_df.iloc[i+j]['change']
                if change > 0: 
                    pos.append(change)
                elif change < 0: 
                    neg.append(abs(change))
                    
            if not neg:
                rsi_value = 100
            elif not pos:
                rsi_value = 0
            else:
                pos = sum(pos)/len(pos)
                neg = sum(neg)/len(neg)
                rsi_value = 100 - (100/(1+(pos/neg)))
            rsi.append(rsi_value)
        except:
            rsi.append(None)
    stock_df.insert(loc=0, column='RSI', value=rsi)

In [20]:
def MFI(stock_df, period = 50):
    stock_df.drop(columns='MFI', inplace=True, errors='ignore')
    mfi = []
    for i in range(len(stock_df)):
        try:
            mfi_value = 0
            pos = []
            neg = []
            typical_prices = []
            
            for j in range(period):
                if not typical_prices: typical_prices.append( mean([stock_df.iloc[i+1]['high'] , stock_df.iloc[i+1]['low'] , stock_df.iloc[i+1]['close']]) ) 
                tp = (stock_df.iloc[i+j]['high'] + stock_df.iloc[i+j]['low'] + stock_df.iloc[i+j]['close']) / 3
                if tp > typical_prices[-1]: 
                    pos.append( tp * stock_df.iloc[i+j]['volume'] )
                elif tp < typical_prices[-1]: 
                    neg.append( tp * stock_df.iloc[i+j]['volume'] )
            
            if not neg:
                mfi_value = 100
            elif not pos:
                mfi_value = 0
            else:
                pos = sum(pos)/len(pos)
                neg = sum(neg)/len(neg)
                mfi_value = 100 - (100/(1+(pos/neg)))
            mfi.append(mfi_value)
        except:
            mfi.append(None)
    stock_df.insert(loc=0, column='MFI', value=mfi)

In [21]:
def EMA(stock_df, period=50):
    stock_df.drop(columns='EMA', inplace=True, errors='ignore')
    a = 2/(period + 1)
    # There are many ways to calculate the first term of an exponential moving average, so for now
    # I'll be using the average of the previous 3 closes
    initial_value_range = 3
    ema = []
    
    for i in range(len(stock_df)):
        emas = []
        try:
            
            for j in list(reversed(range(period))):
                if not emas: emas.append( mean([stock_df.iloc[i+j+day]['close'] for day in range(initial_value_range)]) )
                tc = stock_df.iloc[i+j]['close']
                this_ema = (a * tc) + ((1 - a) * emas[-1])
                emas.append(this_ema)
            
            ema.append(emas[-1])
        except:
            ema.append(None)
    stock_df.insert(loc=0, column='EMA', value=ema)

In [22]:
def SO(stock_df, period=50):
    stock_df.drop(columns='SO', inplace=True, errors='ignore')
    
    so = []
    
    for i in range(len(stock_df)):
        try:
            tc = stock_df.iloc[i]['close']
            ll = min([stock_df.iloc[i+day]['low'] for day in range(period)])
            hh = max([stock_df.iloc[i+day]['high'] for day in range(period)])
            this_so = ((tc - ll) / (hh - ll)) * 100
            so.append(this_so)
        except:
            so.append(None)
    
    stock_df.insert(loc=0, column='SO', value=so)

In [23]:
def MACD(stock_df, p1=12, p2=26):
    stock_df.drop(columns='MACD', inplace=True, errors='ignore')
    
    a1 = 2/(p1 + 1)
    a2 = 2/(p2 + 1)
    initial_value_range = 3
    macd = []
    
    for i in range(len(stock_df)):
        ema1 = []
        ema2 = []
        try:
            for j in list(reversed(range(p1))):
                if not ema1: ema1.append( mean([stock_df.iloc[i+j+day]['close'] for day in range(initial_value_range)]) )
                tc = stock_df.iloc[i+j]['close']
                this_ema = (a1 * tc) + ((1 - a1) * ema1[-1])
                ema1.append(this_ema)
            
            for j in list(reversed(range(p2))):
                if not ema2: ema2.append( mean([stock_df.iloc[i+j+day]['close'] for day in range(initial_value_range)]) )
                tc = stock_df.iloc[i+j]['close']
                this_ema = (a2 * tc) + ((1 - a2) * ema2[-1])
                ema2.append(this_ema)
            
            macd.append(ema1[-1] - ema2[-1])
            
        except:
            macd.append(None)
    
    stock_df.insert(loc=0, column='MACD', value=macd)

In [24]:
# Calculate features for index data, MFI is not calculated as it requires volume

change(index_df)
MACD(index_df)
SO(index_df, 10)
EMA(index_df, 10)
RSI(index_df, 10)
PMO(index_df, 10)
index_df.fillna(value=pd.np.nan, inplace=True)
index_df.dropna(inplace=True)
index_df

,PMO,RSI,EMA,SO,MACD,change,open,high,low,close,adjClose
date,,,,,,,,,,,
2019-10-15,203.73,45.494376,4789.400626,96.126239,-11.328979,1.637409,4862.96,4936.89,4862.02,4923.56,4923.56
2019-10-14,72.56,46.146846,4763.637627,85.050396,-24.624236,0.046262,4835.49,4853.02,4825.67,4844.24,4844.24
2019-10-11,110.23,48.735310,4751.852939,84.292769,-27.004312,1.952511,4831.75,4888.44,4826.66,4842.00,4842.00
2019-10-10,-86.90,43.922339,4732.665429,66.622674,-28.491897,0.779624,4708.95,4778.90,4708.39,4749.27,4749.27
2019-10-09,-110.08,41.845544,4730.846500,46.171345,-26.186076,1.507799,4701.48,4735.08,4688.74,4712.53,4712.53
2019-10-08,-104.78,42.182177,4735.260976,19.181832,-16.470688,-2.568155,4715.00,4719.54,4642.19,4642.53,4642.53
2019-10-07,-65.23,45.020605,4754.067485,64.235865,-2.917925,-0.453973,4774.02,4804.59,4763.99,4764.90,4764.90
2019-10-04,-30.94,37.910602,4758.462698,72.345587,5.864210,1.590512,4737.42,4789.64,4731.57,4786.63,4786.63
2019-10-03,-166.23,36.091735,4754.389489,40.477244,9.066715,1.409102,4648.34,4714.44,4592.78,4711.69,4711.69
2019-10-02,-248.90,35.472316,4767.951462,9.351685,18.114728,-1.559590,4672.11,4682.00,4617.14,4646.22,4646.22
2019-10-01,-179.05,40.218475,4795.245172,10.885285,28.067091,-1.086619,4800.04,4827.67,4707.91,4719.83,4719.83
2019-09-30,-108.66,37.697961,4812.524147,33.070900,36.313494,0.843448,4747.60,4786.06,4735.20,4771.68,4771.68
2019-09-27,-170.00,38.631977,4822.128388,15.994181,36.376915,-2.158733,4821.20,4825.48,4694.39,4731.77,4731.77
2019-09-26,-83.37,47.377465,4843.768023,59.122284,46.979655,0.281176,4825.09,4852.14,4795.32,4836.17,4836.17
2019-09-25,-91.73,45.574469,4843.492192,46.075148,52.435816,1.586161,4730.01,4834.99,4697.41,4822.61,4822.61
2019-09-24,-105.52,41.961002,4845.920100,7.755323,64.307963,-1.714654,4853.31,4860.73,4728.66,4747.31,4747.31
2019-09-23,-27.52,54.100491,4864.444012,18.545646,80.775900,0.260712,4810.44,4849.89,4803.98,4830.13,4830.13
2019-09-20,-35.87,51.850267,4872.034695,11.185984,78.832600,-1.237208,4879.84,4886.55,4798.48,4817.57,4817.57
2019-09-19,27.87,59.026174,4878.364513,44.912132,80.910063,-0.351370,4904.62,4928.10,4873.31,4877.92,4877.92
2019-09-18,166.13,75.358690,4869.920177,55.299233,76.789568,-0.076752,4887.84,4897.07,4829.89,4895.12,4895.12
2019-09-17,262.24,75.520580,4857.015256,73.475782,76.969366,0.379892,4870.73,4901.10,4856.48,4898.88,4898.88
2019-09-16,186.93,65.801360,4843.943988,75.026015,73.209919,-0.437189,4854.95,4895.81,4843.29,4880.34,4880.34
2019-09-13,223.73,62.193460,4834.340554,81.052957,72.639357,-0.361213,4920.92,4932.11,4894.90,4901.77,4901.77
2019-09-12,332.75,61.604318,4815.112805,86.050567,77.674576,0.105813,4941.75,4969.14,4908.78,4919.54,4919.54
2019-09-11,332.49,61.609960,4787.364799,99.977387,71.828935,1.267508,4866.33,4914.43,4855.11,4914.34,4914.34
2019-09-10,256.97,65.455064,4757.076462,90.129675,56.879010,-0.099225,4833.14,4853.68,4803.55,4852.83,4852.83
2019-09-09,312.88,57.685989,4741.942124,91.421070,41.949943,0.086743,4883.44,4889.67,4833.59,4857.65,4857.65
2019-09-06,148.94,41.633221,4719.131670,92.929822,20.338678,0.069896,4856.10,4879.08,4833.53,4853.44,4853.44
2019-09-05,142.57,52.063394,4696.260233,92.162767,-4.701709,2.559955,4812.64,4878.42,4812.64,4850.05,4850.05
2019-09-04,63.40,46.330912,4662.337957,98.003596,-34.387475,1.991744,4705.54,4733.32,4704.25,4728.99,4728.99
...,...,...,...,...,...,...,...,...,...,...,...
2015-01-07,-111.70,19.790908,2351.376424,17.207344,-11.384251,0.747138,2291.59,2310.48,2284.14,2300.44,2300.44
2015-01-06,-101.91,25.798106,2361.567706,5.981444,-10.658356,-1.879155,2330.57,2330.61,2274.29,2283.38,2283.38
2015-01-05,-54.98,27.741241,2375.036397,5.291814,-5.565375,-1.617922,2354.90,2359.20,2321.57,2327.11,2327.11
2015-01-02,35.16,53.441854,2381.822524,22.926953,-0.399299,-0.104314,2379.03,2387.81,2347.27,2365.38,2365.38
2014-12-31,79.61,53.798788,2382.291408,59.070843,5.432838,-0.956616,2399.08,2405.62,2366.24,2367.85,2367.85
2014-12-30,77.51,52.331291,2384.778369,75.096349,10.805246,-0.600789,2397.27,2403.29,2387.07,2390.72,2390.72
2014-12-29,76.19,51.459042,2386.816730,85.221778,14.559983,-0.466389,2412.80,2413.88,2404.03,2405.17,2405.17
2014-12-26,55.29,43.037822,2384.185845,93.118912,15.168013,0.101906,2419.10,2423.64,2414.99,2416.44,2416.44
2014-12-24,64.82,44.802588,2379.852650,91.395137,15.793031,0.039370,2419.01,2422.17,2412.37,2413.98,2413.98
2014-12-23,30.61,46.420984,2372.874380,90.729451,15.687925,0.036897,2422.95,2426.26,2412.83,2413.03,2413.03
2014-12-22,27.42,55.838625,2367.032955,99.844708,14.702963,1.125649,2393.01,2412.34,2392.94,2412.14,2412.14
2014-12-19,-25.77,55.304557,2357.628344,78.752225,11.150787,0.134336,2386.28,2394.25,2375.02,2385.29,2385.29
2014-12-18,-19.49,56.631927,2352.533006,76.275254,8.232048,2.225970,2365.20,2382.09,2355.72,2382.09,2382.09
2014-12-17,-70.01,42.371929,2344.442731,36.125087,6.311841,1.834598,2290.26,2335.80,2283.55,2330.22,2330.22
2014-12-16,-90.66,32.823076,2346.325799,0.360144,8.684851,-1.079452,2298.68,2337.99,2287.79,2288.24,2288.24
2014-12-15,-55.42,33.133941,2358.941243,9.575725,15.860154,-0.677120,2339.63,2354.11,2302.67,2313.21,2313.21
2014-12-12,-67.18,31.017981,2369.005159,0.000000,20.872180,-1.362472,2340.98,2360.78,2328.98,2328.98,2328.98
2014-12-11,-23.95,32.973427,2377.858214,22.781021,25.169614,0.510395,2362.84,2386.88,2356.49,2361.15,2361.15
2014-12-10,-9.97,37.396879,2380.162467,4.834606,28.487102,-1.396059,2381.68,2392.42,2345.93,2349.16,2349.16
2014-12-09,21.01,47.814613,2384.884086,48.688441,34.187402,-0.096447,2358.77,2394.26,2353.65,2382.42,2382.42
2014-12-08,41.72,43.096128,2384.079637,59.243636,38.993618,-1.092466,2401.08,2412.74,2370.58,2384.72,2384.72
2014-12-05,86.70,49.755595,2381.791871,100.000000,43.168776,0.394740,2404.57,2411.06,2400.80,2411.06,2411.06
2014-12-04,88.10,50.135524,2374.468960,93.042855,45.226715,0.056245,2400.55,2409.34,2386.97,2401.58,2401.58
2014-12-03,73.78,54.071040,2367.591098,96.888006,45.258496,0.896633,2381.12,2403.52,2377.40,2400.23,2400.23
2014-12-02,68.28,52.985272,2360.757881,76.857468,47.698615,0.433584,2367.30,2381.37,2362.64,2378.90,2378.90
2014-12-01,52.18,58.292955,2355.190055,67.781183,50.624853,-1.148922,2387.37,2391.04,2362.80,2368.63,2368.63
2014-11-28,99.18,70.924674,2351.697593,93.734138,54.236761,0.463712,2390.21,2403.32,2384.69,2396.16,2396.16
2014-11-26,91.39,69.580662,2340.521147,99.227521,56.016566,1.100830,2360.57,2385.85,2360.13,2385.10,2385.10
2014-11-25,68.00,64.536231,2330.464920,87.248247,57.771101,-0.096552,2364.35,2370.59,2356.98,2359.13,2359.13
2014-11-24,67.62,64.049389,2323.441818,99.654193,63.597300,0.785745,2347.34,2361.69,2343.99,2361.41,2361.41

In [25]:
# Calculate features and labels for stock data, this takes a lot of time
i=0
for df in stocks_df:
    i += 1
    change(df)
    MACD(df)
    SO(df, 10)
    EMA(df, 10)
    MFI(df, 10)
    RSI(df, 10)
    PMO(df, 10)
    for m in [1, 5, 10, 20, 90, 270]:
        labels(df, m)
    df.fillna(value=pd.np.nan, inplace=True)
    print(f'{round(i*100/len(ndxt_tickers))}% ', end='')
    
#for df in stocks_df:
#    df.dropna(inplace=True)

stocks_df[-1].head()

3% 5% 8% 10% 13% 15% 18% 21% 23% 26% 28% 31% 33% 36% 38% 41% 44% 46% 49% 51% 54% 56% 59% 62% 64% 67% 69% 72% 74% 77% 79% 82% 85% 87% 90% 92% 95% 97% 100%

                   y_270  y_90  y_20  y_10  y_5  y_1   PMO        RSI  \
symbol date
XLNX   2019-10-15    NaN   NaN   NaN   NaN  NaN  NaN  4.93  45.699143
       2019-10-14    NaN   NaN   NaN   NaN  NaN  1.0  0.03  40.792760
       2019-10-11    NaN   NaN   NaN   NaN  NaN  0.0  0.27  41.425551
       2019-10-10    NaN   NaN   NaN   NaN  NaN  1.0 -4.43  37.015132
       2019-10-09    NaN   NaN   NaN   NaN  NaN  1.0 -6.71  26.073207

                          MFI        EMA  ...  adjClose  adjHigh   adjLow  \
symbol date                               ...
XLNX   2019-10-15   52.600614  94.139094  ...     96.97    97.45  95.8916
       2019-10-14   49.954551  93.624320  ...     95.93    98.86  95.5600
       2019-10-11   44.948593  93.382899  ...     96.22    98.15  94.9300
       2019-10-10   50.002449  92.797889  ...     92.81    94.32  90.5000
       2019-10-09  100.000000  92.816159  ...     90.48    91.21  89.6700

                   adjOpen  adjVolume  close   high      low   open   volume
symbol date
XLNX   2019-10-15    96.24    2774611  96.97  97.45  95.8916  96.24  2774611
       2019-10-14    98.31    3812968  95.93  98.86  95.5600  98.31  3812968
       2019-10-11    95.12    4909771  96.22  98.15  94.9300  95.12  4909771
       2019-10-10    90.61    2883108  92.81  94.32  90.5000  90.61  2883108
       2019-10-09    90.70    3246725  90.48  91.21  89.6700  90.70  3246725

[5 rows x 23 columns]

In [26]:
stocks_df[0].tail()

                   y_270  y_90  y_20  y_10  y_5  y_1  PMO  RSI  MFI  EMA  ...  \
symbol date                                                               ...
ADBE   2014-10-22    1.0   1.0   1.0   1.0  1.0  1.0  NaN  NaN  NaN  NaN  ...
       2014-10-21    1.0   1.0   1.0   1.0  1.0  0.0  NaN  NaN  NaN  NaN  ...
       2014-10-20    1.0   1.0   1.0   1.0  1.0  1.0  NaN  NaN  NaN  NaN  ...
       2014-10-17    1.0   1.0   1.0   1.0  1.0  1.0  NaN  NaN  NaN  NaN  ...
       2014-10-16    1.0   1.0   1.0   1.0  1.0  1.0  NaN  NaN  NaN  NaN  ...

                   adjClose  adjHigh  adjLow  adjOpen  adjVolume   close  \
symbol date
ADBE   2014-10-22    65.040    66.49   64.99    66.31    2363348  65.040
       2014-10-21    66.425    66.56   64.51    64.84    3229897  66.425
       2014-10-20    64.680    64.73   63.70    64.25    4266231  64.680
       2014-10-17    64.520    65.13   63.46    63.46    6540794  64.520
       2014-10-16    62.860    63.72   60.72    60.72    6639958  62.860

                    high    low   open   volume
symbol date
ADBE   2014-10-22  66.49  64.99  66.31  2363348
       2014-10-21  66.56  64.51  64.84  3229897
       2014-10-20  64.73  63.70  64.25  4266231
       2014-10-17  65.13  63.46  63.46  6540794
       2014-10-16  63.72  60.72  60.72  6639958

[5 rows x 23 columns]

In [27]:
# Save the processed data as a milestone

index_df.to_csv(processed_data_dir+ '^NDXT.csv')
for df in stocks_df:
    df.to_csv(processed_data_dir+ f'{df.index[0][0]}.csv')

In [28]:
# Normalizing features
scaler = MinMaxScaler()

idf = index_df[['PMO', 'EMA', 'MACD']]
scaler.fit(idf)
index_df[['PMO', 'EMA', 'MACD']] = scaler.transform(idf)
idf = index_df[['RSI', 'SO']]
index_df[['RSI', 'SO']] = idf/100

for i, df_ in enumerate(stocks_df):
    df = df_[['PMO', 'EMA', 'MACD']]
    scaler.fit(df)
    stocks_df[i][['PMO', 'EMA', 'MACD']] = scaler.transform(df)
    df = df_[['RSI' ,'MFI', 'SO']]
    stocks_df[i][['RSI' ,'MFI', 'SO']] = df/100

In [29]:
len(stocks_df[0][['y_'+str(1), 'PMO', 'EMA', 'MACD', 'RSI' ,'MFI', 'SO']].to_numpy())

1258

In [30]:
len(index_df[['PMO', 'EMA', 'MACD', 'RSI', 'SO']].to_numpy())

1231

In [31]:
np.hstack([stocks_df[0][['y_'+str(1), 'PMO', 'EMA', 'MACD', 'RSI' ,'MFI', 'SO']].to_numpy(), index_df[['PMO', 'EMA', 'MACD', 'RSI', 'SO']].to_numpy()])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
pd.concat([stocks_df[0][['y_'+str(1), 'PMO', 'EMA', 'MACD', 'RSI' ,'MFI', 'SO']], index_df[['PMO', 'EMA', 'MACD', 'RSI', 'SO']].reset_index().drop(columns='date')], sort=False, axis=1)

In [ ]:
# Unify all data into separate training/testing sets

test_train_separation = round(len(stocks_df[0])*2/3)

for t in time_range:
    new_df_list = []
    
    for df in stocks_df:
        new_df_list.append(pd.concat([df[['y_'+str(t), 'PMO', 'EMA', 'MACD', 'RSI' ,'MFI', 'SO']], index_df[['PMO', 'EMA', 'MACD', 'RSI', 'SO']]], axis=1))
    
    for dataset in new_df_list:
        dataset.iloc[:test_train_separation].to_csv(final_data_dir+str(t)+'/train.csv')
        dataset.iloc[test_train_separation:].to_csv(final_data_dir+str(t)+'/test.csv')

# To think about

## How to sum up data into feedable features
* Definitely by record
## Labels are per row? per group of rows?
* Smaller groups -> more input data.
* These groups are n_1 and n_2 for stocks and index respectively.

## Categorical labels for low to high increase/decrease

## Should all features be normalized? how?
Yes, absolutely. MinMax normalization.